# Generated by Django 4.2.7 on 2026-03-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('is_face_registered', models.BooleanField(default=False)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('face_samples_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_employees',
                'ordering': ['emp_code'],
                'unique_together': {('user', 'emp_code')},
            },
        ),
        migrations.CreateModel(
            name='FaceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/samples/')),
                ('is_processed', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_samples', to='attendance_system.employee')),
            ],
            options={
                'db_table': 'tbl_face_samples',
                'unique_together': {('employee', 'sample_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('liveness_ok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance_system.employee')),
            ],
            options={
                'db_table': 'tbl_attendance',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
